listenAddress: 192.168.1.1:8000

tlsInfo:
  enabled: true
  certFile: cert.pem
  keyFile: key.pem

mainPageInfo:
  title: Aaron's APU2
  cacheControlValue: public, max-age=60
  pushInfo:
    targets: [/style.css]

pprofInfo:
  enabled: true

staticFiles:

- httpPath: /style.css
  filePath: ./style.css
  cacheControlValue: public, max-age=60

staticDirectories:
- httpPath: /vnstat/
  directoryPath: /home/aaron/vnstat

commandPushInfo:
  targets: [/style.css]

commands:

- httpPath: /arp
  description: arp
  command: /usr/sbin/arp
  args: [-an]

- httpPath: /df
  description: df
  command: df
  args: [-h]

- httpPath: /dhcp-lease-list
  description: dhcp lease list
  command: /home/aaron/rust-dhcp-leases/target/release/rust-dhcp-leases

- httpPath: /dmesg
  description: dmesg
  command: sudo
  args: [dmesg]

- httpPath: /ifconfig
  description: ifconfig
  command: /sbin/ifconfig

- httpPath: /lscpu
  description: lscpu
  command: lscpu

- httpPath: /log_ls
  description: log ls
  command: ls
  args: [-latrh, logs]

- httpPath: /log_tail
  description: log tail
  command: tail
  args: [-n30, logs/current]

- httpPath: /ncal
  description: ncal
  command: ncal
  args: [-h, -y]

- httpPath: /netstat_an
  description: netstat -an
  command: netstat
  args: [-a, -n]

- httpPath: /netstat_s
  description: netstat -s
  command: netstat
  args: [-s]

- httpPath: /ntpq
  description: ntpq
  command: ntpq
  args: [-p]

- httpPath: /sensors
  description: sensors
  command: sensors

- httpPath: /top
  description: top
  command: top
  args: [-b, -n1]

- httpPath: /unbound_infra
  description: unbound infra
  command: sudo
  args: [unbound-control, dump_infra]

- httpPath: /unbound_stats
  description: unbound stats
  command: sudo
  args: [unbound-control, stats_noreset]

- httpPath: /uptime
  description: uptime
  command: uptime

- httpPath: /vmstat
  description: vmstat
  command: vmstat

- httpPath: /w
  description: w
  command: w
