listenAddress: :8081

requestLogger:
  filename: logs/request.log
  maxsize: 1
  maxbackups: 10
  localtime: true

mainPageTitle: Aaron's Raspberry Pi

staticFiles:

- httpPath: /style.css
  filePath: ./style.css

- httpPath: /favicon.ico
  filePath: ./favicon.ico

commands:

- httpPath: /ifconfig
  description: ifconfig
  command: /sbin/ifconfig

- httpPath: /iwconfig
  description: iwconfig
  command: /sbin/iwconfig

- httpPath: /netstat
  description: netstat
  command: netstat
  args: [-a, -n]

- httpPath: /ntpq
  description: ntpq
  command: ntpq
  args: [-p]

- httpPath: /pitemp
  description: pitemp
  command: /home/pi/bin/pitemp.sh

- httpPath: /top
  description: top
  command: top
  args: [-b, -n1]

- httpPath: /tail_request_log
  description: tail request log
  command: tail
  args: [-n, 20, logs/request.log]

- httpPath: /uptime
  description: uptime
  command: uptime

- httpPath: /vmstat
  description: vmstat
  command: vmstat

- httpPath: /w
  description: w
  command: w
