listenAddress: :8080

requestLogger:
  filename: request.log
  maxsize: 1
  maxbackups: 10
  localtime: true

mainPageTitle: Aaron's Raspberry Pi

staticFiles:

- httpPath: /style.css
  filePath: ./style.css

- httpPath: /favicon.ico
  filePath: ./openbsd-favicon.ico

commands:

- httpPath: /ifconfig
  description: ifconfig
  command: ifconfig

- httpPath: /iwconfig
  description: iwconfig
  command: iwconfig

- httpPath: /netstat
  description: netstat
  command: netstat
  args: [-a, -n]

- httpPath: /ntpq
  description: ntpq
  command: ntpq
  args: [-p]

- httpPath: /pitemp
  description: pitemp
  command: pitemp.sh

- httpPath: /top
  description: top
  command: top
  args: [-b, -n1]

- httpPath: /uptime
  description: uptime
  command: uptime

- httpPath: /vmstat
  description: vmstat
  command: vmstat

- httpPath: /w
  description: w
  command: w
