listenAddress: :10443

requestLogger:
  filename: logs/request.log
  maxsize: 1
  maxbackups: 10
  localtime: true

tlsInfo:
  enabled: true
  certFile: cert.pem
  keyFile: key.pem

mainPageInfo:
  title: Aaron's Raspberry Pi
  cacheControlValue: public, max-age=60

pprofInfo:
  enabled: true

staticFiles:

- httpPath: /style.css
  filePath: ./style.css
  cacheControlValue: public, max-age=60

- httpPath: /favicon.ico
  filePath: ./favicon.ico
  cacheControlValue: public, max-age=60

commands:

- httpPath: /ifconfig
  description: ifconfig
  command: /sbin/ifconfig

- httpPath: /iwconfig
  description: iwconfig
  command: /sbin/iwconfig

- httpPath: /ncal
  description: ncal
  command: ncal
  args: [-h, -y]

- httpPath: /netstat
  description: netstat
  command: netstat
  args: [-a, -n]

- httpPath: /ntpq
  description: ntpq
  command: ntpq
  args: [-p]

- httpPath: /pitemp
  description: pitemp
  command: /home/pi/bin/pitemp.sh

- httpPath: /top
  description: top
  command: top
  args: [-b, -n1]

- httpPath: /tail_request_log
  description: tail request log
  command: tail
  args: [-n, 20, logs/request.log]

- httpPath: /unbound_infra
  description: unbound infra
  command: sudo
  args: [unbound-control, dump_infra]

- httpPath: /unbound_stats
  description: unbound stats
  command: sudo
  args: [unbound-control, stats_noreset]

- httpPath: /uptime
  description: uptime
  command: uptime

- httpPath: /vmstat
  description: vmstat
  command: vmstat

- httpPath: /w
  description: w
  command: w
