listenAddress: :10443

requestLogger:
  filename: logs/request.log
  maxsize: 1
  maxbackups: 10
  localtime: true

tlsInfo:
  enabled: true
  certFile: cert.pem
  keyFile: key.pem

mainPageInfo:
  title: Server
  cacheControlValue: public, max-age=60
  pushInfo:
    targets: [/style.css]

pprofInfo:
  enabled: true

staticFiles:

- httpPath: /style.css
  filePath: ./style.css
  cacheControlValue: public, max-age=60

- httpPath: /favicon.ico
  filePath: ./favicon.ico
  cacheControlValue: public, max-age=60

staticDirectories:

- httpPath: /pfstat/
  directoryPath: /var/www/htdocs/pfstat

commandPushInfo:
  targets: [/style.css]

commands:

- httpPath: /dhcp-lease-list
  description: dhcp lease list
  command: /home/aaron/rust-dhcp-leases/run_openbsd.sh

- httpPath: /dmesg
  description: dmesg
  command: dmesg

- httpPath: /ifconfig
  description: ifconfig
  command: /sbin/ifconfig

- httpPath: /netstat
  description: netstat
  command: netstat
  args: [-binh]

- httpPath: /ntpctl
  description: ntpctl
  command: ntpctl
  args: [-sa]

- httpPath: /top
  description: top
  command: top
  args: [-b, -n1]

- httpPath: /tail_request_log
  description: tail request log
  command: tail
  args: [-n, 20, logs/request.log]

- httpPath: /unbound_infra
  description: unbound infra
  command: doas
  args: [/usr/sbin/unbound-control, dump_infra]

- httpPath: /unbound_stats
  description: unbound stats
  command: doas
  args: [/usr/sbin/unbound-control, stats_noreset]

- httpPath: /uptime
  description: uptime
  command: uptime

- httpPath: /vmstat
  description: vmstat
  command: vmstat

- httpPath: /w
  description: w
  command: w
