listenAddress: 10.0.0.1:8080

requestLogger:
  filename: request.log
  maxsize: 1
  maxbackups: 10
  localtime: true

mainPageTitle: Aaron's OpenBSD Box

staticFiles:

- httpPath: /style.css
  filePath: ./style.css

- httpPath: /favicon.ico
  filePath: ./openbsd-favicon.ico

staticDirectories:

- httpPath: /pfstat/
  directoryPath: /var/www/htdocs/pfstat/

commands:

- httpPath: /ifconfig
  description: ifconfig
  command: ifconfig

- httpPath: /netstat_an
  description: netstat -an
  command: netstat
  args: [-an]

- httpPath: /netstat_binh
  description: netstat -binh
  command: netstat
  args: [-binh]

- httpPath: /ntpctl
  description: ntpctl
  command: ntpctl
  args: [-sa]

- httpPath: /top
  description: top
  command: top
  args: [-b, -n1]

- httpPath: /unbound_dump_infra
  description: unbound dump_infra
  command: doas
  args: [/usr/sbin/unbound-control, dump_infra]

- httpPath: /unbound_stats_noreset
  description: unbound stats_noreset
  command: doas
  args: [/usr/sbin/unbound-control, stats_noreset]

- httpPath: /uptime
  description: uptime
  command: uptime

- httpPath: /vmstat
  description: vmstat
  command: vmstat

- httpPath: /w
  description: w
  command: w
