listenAddress: :8080

requestLogger:
  filename: request.log
  maxsize: 1
  maxbackups: 10
  localtime: true

staticFiles:
- style.css
- favicon.ico

mainPageTitle: Aaron's OpenBSD Box

commands:

- httpPath: /ifconfig
  description: ifconfig
  command: ifconfig

- httpPath: /netstat
  description: netstat
  command: netstat
  args: [-a, -n]

- httpPath: /ntpctl
  description: ntpctl
  command: ntpctl
  args: [-sa]

- httpPath: /top
  description: top
  command: top
  args: [-b, -n1]

- httpPath: /unbound_dump_infra
  description: unbound dump_infra
  command: doas
  args: [/usr/sbin/unbound-control, dump_infra]

- httpPath: /unbound_stats_noreset
  description: unbound stats_noreset
  command: doas
  args: [/usr/sbin/unbound-control, stats_noreset]

- httpPath: /uptime
  description: uptime
  command: uptime

- httpPath: /vmstat
  description: vmstat
  command: vmstat

- httpPath: /w
  description: w
  command: w
